language: java
jdk:
- oraclejdk8
script:
  - cd src
  - if [[ -z "$TRAVIS_TAG" ]]; then PHASE=package; else PHASE=deploy; fi
  - mvn $PHASE --settings .travis.settings.xml
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: Fr2Kfq1vE4FcPfgD0O56g+J6NbzqjW8UyZMt+vq0Q64aC6IEKz4aFVtFUepu/VAE6HBXxWhGzDZ1hGj8OuUykUtRT5v2wowxvaoEzQcSA5SxRFVE+9apa/JqDu37Q5XqaFW7XE54mNGJ4OjGzlZODmvsGwBnt4Gep1IUrQI6Xviw9vKQsSUiO+m7Lm6sOdQPx22H4Z+gI1MJKP4vgS3qrsXed7QEE4Fvy+2iq5F9O+qijXL1qfc0Q9FlNQxIEaGB2KGyDB4sWTqIV5XJlyKS9V7wZeWcim5sEd122AjeBqIf2eJgOhkqQii/s/ppRQA7FCar4IbfR/EghHRS5v7vtzI7UeCIYP+0uuvBhu09UHJsEm0U556dgCzJOe4JvBpdsYyqVJA7/geCpUO4Np4GB6n0f3avPeQM9eTptk8HlDN7gcpfgclEOcK2nmPPLEySw03VyqfI9wFJL04rqXBxnw8/XmPlhG+u4cpsOQLfvSlNcfiNEu/7m9jhFUpy/rvK5duDkKtAAkvOjuieqKTfYPMgBMN7sARk404yQsKFxTce8753fIvHArCEhfbnK/ocJRSOuz73PI8jbgKHRRACV/PIwcwbtG81ovS30rZFVK6piKX5qTtlIHBQNgNuvwlYT/CZaCIpqgpL2j2aGdiQ+fPM92Qhamlzrqqk8V8qWCo=
  file_glob: true
  file: "*/target/*.zip"
  skip_cleanup: true
  on:
    repo: INTER-IoT/gateway-extensions-physical
    tags: true
    branches:
      only:
        - master
env:
  global:
    - secure: J6kCT8OcB660GcUY799QhrNTu8u9asEvFihDq6ZT8uiDRbhF4rSPFohUQCqHDzzo9ar2DAW8xN1vdV4JyGIS82FJZ6JKYkBqJdHq/9+UTyqQMzVf37cWGaP01AvyM9T8NlZOSga50NQbbYE2bG4eBt5yFs6BYxyXlJgOHQbi4XlSIaizMRbgZBIJ6/iV3WsNRwNMYL6uDuieN4JZeaBuWFQxFzQIlqVu4bkn0GtFYT7trE6LrVXOTWtcvXKea70n+9XwhjOfAjvMZohzKcOBENI6yqOADAMTGh9shnmUSEn/bRDbVVsFuDl2tvCpMkirUHYJ3Q9DsV/oYy5STZ8hekT7074sQNvwTEw/q34LzLrqBwtP71ZbqjIpaUKoYf4whFcOHc94iavx6EKWrHLdeh80Xre76vi4nhCdLb3ApvnAeWk4IEQmKYKkMmrkRzAbMiBxVg0powp8RqxnBoljdhiyK4EDdzExDiCF5rYhyDB6tvo0mWUqPOtoMEw/WiQTVhPfmWJsgVrFS6a1r7alm36tpVAdVo33GfwahqPq7WZ+fTjjltfrgZr9d2Pc8ZVn2FBxH7eFuWRYsQLqS1T0w/2Tuw3uxqsNvJhdmrbpcbzRWo/hKGHepaGjK38W78c7jpXbpuP8QCOaRTzNHr87u0ECrQy2yI54PX2lGwA8k68=
    - secure: BAmla8xRjVQB9QwmJSe3cdCD3lds0DC1eEzB+2qrdm5uK5kV6zDOcHbwJBmO4v+Nqr2GyhIL4kCI/dvJr4jQxTetXRhZch+zrZL6sbgp0c51Kget7AizHgDrWW8YO4u91ZbdfWf0eYfe7/Qwer5i8N2f0B1GIXUu2E7mJvCtIthpwl3iB43IvXp8Kn5fKFq6tAh4IxbgwpyezMXX/9OG0TH06Du945c+Fxqxt2tbatl9b+RIffd9NVgM/LENItNHGVDJmJxuWGKgaam0fMbgEyVYHx3WCxnIisf+dV6dzlaMVuS/SrfDU629q9TMubcLgpSAQjqlY8VKirHhxZzwdhDzSiOVPI1/56ql1vAU1oST2VptkM79dCwSJXgeORK6vBJT1yY19jTbDiiyFWoWIXGBVB9blxiqJSmmDxEM/mdeThbuWs7b6ZqtFGpipWpWVaimfB2eggC1zbQFmwvICMALXq9tqf3ioqV/me9n7GW0brKIQ9FmjUDyV1EPTPIl4UJG3ud8wjrliaZvFMXnkhfmnCdQRb/jitEh6dCP8/bVAevIuKXQmRfQpQQI9t8JOD/oF7qmNR9EgmO8VDVRz5TB9fL80CXNQaByB6f2sTnGTdkjAmxnRwuLuai2mJcL/LNFuCrMvOKYBeeKP0e/FvKKW6dORDOIxdgP4/bZzME=
